# Generated by Django 5.0.6 on 2024-05-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='blog',
            name='github_url',
            field=models.URLField(default='este es un campo adicional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/profile_picturies/pngwing.com_1.png', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
